console.log("My First Console");
var name1="GURU";
var name2="Preetham";
var name=name1.concat(name2);
console.log(name);
var a=10;
var b=5;
var add=a+b;
console.log(add);
var sub=a-b;
console.log(sub);
